var Competition = require('./model/competition');
var CompetitionType = require('./model/competition_type');
var Invitation = require('./model/invitation');
var Performance = require('./model/performance');
var Token = require('./model/token');
var TokenSource = require('./model/token_source');
var User = require('./model/user');
var Validation = require('./model/validation');

Competition.belongsTo(CompetitionType);
Competition.belongsToMany(Performance, { through: 'competition_performances' });
CompetitionType.hasMany(Competition);
Invitation.belongsTo(User);
Performance.belongsToMany(Competition, { through: 'competition_performances' });
Performance.hasMany(Validation);
Token.belongsTo(TokenSource);
Token.belongsTo(User);
TokenSource.hasMany(Token);
User.hasMany(Token);
User.hasMany(Validation);
User.hasMany(Performance);
User.hasMany(Invitation);
User.belongsToMany(User, { through: 'user_follows', as: 'follow_user' });
Validation.belongsTo(Performance);
